import {describe,expect,test} from "bun:test";
import {AgentEventDaemon,AgentEventLedger,AGENT_EVENT_SCHEMA} from "../src/agent-event-ledger";
import {AgentEventHttpIngress,DiscordMarkerAdapter,GitHubMarkerAdapter,loadAgentEventDaemonConfig,signTrustedDiscordRow} from "../src/agent-event-daemon";
import {ProjectRegistry} from "../src/project-routes";
const route={name:"livesiang",transport:"discord-text" as const,destination:"1537404238861438996",agent:"03-canon:1",issue:"natkingsize2/liveSiang#15"};
const seq=(start:number)=>Buffer.from(Array.from({length:32},(_,i)=>start+i)).toString("base64");
const env={MAW_AGENT_EVENT_HTTP_TOKEN:"A".repeat(32),MAW_AGENT_EVENT_AUTHOR_ID:"1056224550129508415",MAW_AGENT_EVENT_INGRESS_KEY_B64:seq(1),MAW_AGENT_EVENT_STORE_KEY_B64:seq(65)};
describe("production daemon seam",()=>{
 test("config rejects missing, noncanonical, repeated, and equal secrets",()=>{for(const e of[{}, {...env,MAW_AGENT_EVENT_INGRESS_KEY_B64:Buffer.alloc(32).toString("base64")},{...env,MAW_AGENT_EVENT_STORE_KEY_B64:env.MAW_AGENT_EVENT_INGRESS_KEY_B64},{...env,MAW_AGENT_EVENT_STORE_KEY_B64:env.MAW_AGENT_EVENT_STORE_KEY_B64.replace(/=$/,"")}])expect(()=>loadAgentEventDaemonConfig(e)).toThrow("configuration invalid");});
 test("trusted row HTTP accepts then duplicate replay",async()=>{const cfg=loadAgentEventDaemonConfig(env),calls:string[]=[];const ledger=new AgentEventLedger(new ProjectRegistry([route]),{emitDiscord:async()=>{calls.push("d")},emitGitHub:async()=>{calls.push("g")}},undefined,()=>"2026-08-14T15:45:01.000Z",cfg.authority);const http=new AgentEventHttpIngress(new AgentEventDaemon(ledger),cfg);const signed=signTrustedDiscordRow({authorId:cfg.authority.authorId,authorIsBot:false,webhookId:null,channelId:route.destination,projectRoute:route.name,messageId:"1537404238861438997",timestamp:"2026-08-14T15:45:00.000Z",event:{schema:AGENT_EVENT_SCHEMA,project:route.name,kind:"done",event_id:"e-http",agent:"canon",summary:"done",occurred_at:"2026-08-14T15:45:00.000Z"}},cfg.authority);const req=()=>new Request("http://127.0.0.1/agent-event",{method:"POST",headers:{Authorization:`Bearer ${cfg.httpToken}`},body:JSON.stringify(signed)});expect((await http.handle(req())).status).toBe(202);expect((await http.handle(req())).status).toBe(200);expect(calls).toEqual(["d","g"]);});
 test("wrong bearer and webhook row fail before ledger",async()=>{const cfg=loadAgentEventDaemonConfig(env);expect(()=>signTrustedDiscordRow({authorId:cfg.authority.authorId,authorIsBot:false,webhookId:"1537404238861438998",channelId:route.destination,projectRoute:route.name,messageId:"1537404238861438997",timestamp:new Date().toISOString(),event:{} as any},cfg.authority)).toThrow("rejected");const http=new AgentEventHttpIngress(new AgentEventDaemon(new AgentEventLedger(new ProjectRegistry([route]),{emitDiscord:async()=>{},emitGitHub:async()=>{}},undefined,undefined,cfg.authority)),cfg);expect((await http.handle(new Request("http://127.0.0.1/agent-event",{method:"POST",body:"{}"}))).status).toBe(401);});
 test("marker adapters paginate, ignore outsider/webhook, and hold ambiguity",async()=>{const d=new DiscordMarkerAdapter({listOwnMessages:async(_c,b)=>b?[{id:"51",authorId:"bot",webhookId:null,marker:"key"}]:Array.from({length:50},(_,i)=>({id:String(i),authorId:i===0?"outsider":"bot",webhookId:i===1?"hook":null,marker:i<2?"key":"other"}))},"bot");expect(await d.has(route.destination,"key")).toBe(true);const g=new GitHubMarkerAdapter({listComments:async()=>[{id:"1",actor:"bot",marker:"key"},{id:"2",actor:"bot",marker:"key"}]},"bot");await expect(g.has(route.issue,"key")).rejects.toThrow("ambiguous");});
});
