import { afterEach, describe, expect, test } from "bun:test";
import { chmodSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { AGENT_EVENT_SCHEMA, AgentEventLedger, signAgentEventIngress, type AuthenticatedAgentEventIngress, type OutboundEmitter } from "../src/agent-event-ledger";
import { ProjectRegistry, type ProjectRoute } from "../src/project-routes";
const ROUTES:ProjectRoute[]=[{name:"livesiang",transport:"discord-text",destination:"1537404238861438996",agent:"03-canon:1",issue:"natkingsize2/liveSiang#15"}];
const registry=new ProjectRegistry(ROUTES); const open:AgentEventLedger[]=[]; afterEach(()=>{for(const l of open.splice(0))l.close()});
const ev=(o:Record<string,unknown>={})=>({schema:AGENT_EVENT_SCHEMA,project:"livesiang",kind:"progress",event_id:"e1",agent:"canon",summary:"งานคืบหน้า",occurred_at:"2026-08-14T15:45:00.000Z",...o});
function emitter(fail?:"discord"|"github"){const calls:{sink:string;key?:string}[]=[];return{calls,value:{emitDiscord:async(_d:string,_c:string,key?:string)=>{calls.push({sink:"discord",key});if(fail==="discord")throw Error("down")},emitGitHub:async(_i:string,_c:string,key?:string)=>{calls.push({sink:"github",key});if(fail==="github")throw Error("down")}} satisfies OutboundEmitter};}
function root(prefix="ael-"){return mkdtempSync(join(tmpdir(),prefix))} function path(r:string){return join(r,"ledger.json")}

describe("transactional durable outbox",()=>{
 test("persists pending before send and resumes only unfinished sink with stable key",async()=>{const r=root();const a=emitter("github");const l=new AgentEventLedger(registry,a.value,path(r));open.push(l);await expect(l.accept(ev())).rejects.toThrow("down");expect(a.calls.map(x=>x.sink)).toEqual(["discord","github"]);const snap=JSON.parse(readFileSync(path(r),"utf8"));expect(snap.records["agent-event-v1:livesiang:e1"].sinks.discord.status).toBe("delivered");expect(snap.records["agent-event-v1:livesiang:e1"].sinks.github.status).toBe("pending");const key=a.calls[1]!.key;l.close();open.pop();const b=emitter();const l2=new AgentEventLedger(registry,b.value,path(r));open.push(l2);expect((await l2.accept(ev())).status).toBe("duplicate");expect(b.calls).toEqual([{sink:"github",key}]);});
 test("full canonical event digest catches non-summary mutation",async()=>{const l=new AgentEventLedger(registry,emitter().value);await l.accept(ev());await expect(l.accept(ev({agent:"other"}))).rejects.toThrow("idempotency conflict");});
 test("snapshot digest binds records and audit",async()=>{const r=root();const l=new AgentEventLedger(registry,emitter().value,path(r));open.push(l);await l.accept(ev());l.close();open.pop();const s=JSON.parse(readFileSync(path(r),"utf8"));s.records["agent-event-v1:livesiang:e1"].event.agent="tampered";writeFileSync(path(r),JSON.stringify(s),{mode:0o600});expect(()=>new AgentEventLedger(registry,emitter().value,path(r))).toThrow("snapshot digest mismatch");});
});

describe("authority and store",()=>{
 test("signed ingress binds author bot channel and project route",async()=>{const key=Buffer.alloc(32,7);const l=new AgentEventLedger(registry,emitter().value,undefined,undefined,{authorId:"owner",key});const unsigned={event:ev(),authorId:"owner",authorIsBot:false,channelId:ROUTES[0]!.destination,projectRoute:"livesiang"};const good={...unsigned,signature:signAgentEventIngress(unsigned,key)};expect((await l.acceptAuthenticated(good)).status).toBe("accepted");for(const mutation of [{authorIsBot:true},{channelId:"1537404238861438997"},{projectRoute:"wrong"},{authorId:"other"}]){const u={...unsigned,...mutation};const x={...u,signature:signAgentEventIngress(u,key)} as AuthenticatedAgentEventIngress;await expect(l.acceptAuthenticated(x)).rejects.toThrow("ingress");}});
 test("rejects unsigned direct accept when authority configured",async()=>{const l=new AgentEventLedger(registry,emitter().value,undefined,undefined,{authorId:"owner",key:Buffer.alloc(32)});await expect(l.accept(ev())).rejects.toThrow("authenticated ingress required");});
 test("creates 0700 root/0600 snapshot; rejects unsafe and symlink roots",async()=>{const parent=root();const made=join(parent,"store");const l=new AgentEventLedger(registry,emitter().value,path(made));open.push(l);await l.accept(ev());expect(Bun.file(path(made)).size).toBeGreaterThan(0);expect((await import("node:fs")).statSync(made).mode&0o777).toBe(0o700);expect((await import("node:fs")).statSync(path(made)).mode&0o777).toBe(0o600);l.close();open.pop();chmodSync(made,0o755);expect(()=>new AgentEventLedger(registry,emitter().value,path(made))).toThrow("root unsafe");const link=join(parent,"link");symlinkSync(made,link);expect(()=>new AgentEventLedger(registry,emitter().value,path(link))).toThrow("root unsafe");});
 test("single writer lease rejects concurrent process and releases cleanly",async()=>{const r=root();const l=new AgentEventLedger(registry,emitter().value,path(r));open.push(l);const child=Bun.spawn([process.execPath,"-e",`import {AgentEventLedger} from ${JSON.stringify(new URL("../src/agent-event-ledger.ts",import.meta.url).href)};import {ProjectRegistry} from ${JSON.stringify(new URL("../src/project-routes.ts",import.meta.url).href)};new AgentEventLedger(new ProjectRegistry(${JSON.stringify(ROUTES)}),{emitDiscord:async()=>{},emitGitHub:async()=>{}},${JSON.stringify(path(r))});`],{stdout:"pipe",stderr:"pipe"});expect(await child.exited).not.toBe(0);l.close();open.pop();const l2=new AgentEventLedger(registry,emitter().value,path(r));open.push(l2);});
 test("recovers a lease left by a crashed writer process",async()=>{const r=root();const script=`import {AgentEventLedger} from ${JSON.stringify(new URL("../src/agent-event-ledger.ts",import.meta.url).href)};import {ProjectRegistry} from ${JSON.stringify(new URL("../src/project-routes.ts",import.meta.url).href)};new AgentEventLedger(new ProjectRegistry(${JSON.stringify(ROUTES)}),{emitDiscord:async()=>{},emitGitHub:async()=>{}},${JSON.stringify(path(r))});` ;const child=Bun.spawn([process.execPath,"-e",script]);expect(await child.exited).toBe(0);const successor=new AgentEventLedger(registry,emitter().value,path(r));open.push(successor);});
});
