import { afterEach, describe, expect, test } from "bun:test";
import { chmodSync, mkdtempSync, readFileSync, realpathSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os"; import { join } from "node:path";
import { AGENT_EVENT_SCHEMA,AgentEventLedger,signAgentEventIngress,type AuthenticatedAgentEventIngress,type LeaseProbe,type OutboundEmitter } from "../src/agent-event-ledger";
import { ProjectRegistry,type ProjectRoute } from "../src/project-routes";
const ROUTES:ProjectRoute[]=[{name:"livesiang",transport:"discord-text",destination:"1537404238861438996",agent:"03-canon:1",issue:"natkingsize2/liveSiang#15"}];
const registry=new ProjectRegistry(ROUTES), STORE=Buffer.alloc(32,9), AUTH=Buffer.alloc(32,7), OWNER="1056224550129508415";
const opened:AgentEventLedger[]=[];afterEach(()=>opened.splice(0).forEach(x=>x.close()));
const ev=(o:Record<string,unknown>={})=>({schema:AGENT_EVENT_SCHEMA,project:"livesiang",kind:"progress",event_id:"e1",agent:"canon",summary:"งานคืบหน้า",occurred_at:"2026-08-14T15:45:00.000Z",...o});
const root=()=>realpathSync(mkdtempSync(join(tmpdir(),"ael-"))), db=(r:string)=>join(r,"ledger.json");
function fake(fail?:"discord"|"github",markers=new Set<string>()){const calls:string[]=[];const value:OutboundEmitter={hasDiscord:async(_d,k)=>markers.has(k),hasGitHub:async(_d,k)=>markers.has(k),emitDiscord:async(_d,_c,k)=>{calls.push(`discord:${k}`);markers.add(k!);if(fail==="discord")throw Error("lost ack")},emitGitHub:async(_d,_c,k)=>{calls.push(`github:${k}`);markers.add(k!);if(fail==="github")throw Error("lost ack")}};return{value,calls,markers};}
function durable(r:string,e:OutboundEmitter){const l=new AgentEventLedger(registry,e,db(r),undefined,undefined,STORE);opened.push(l);return l;}

describe("outbox and concurrency",()=>{
 test("lost sink ack reconciles marker without repost after crash/restart",async()=>{const r=root(),a=fake("github");const l=durable(r,a.value);await expect(l.accept(ev())).rejects.toThrow("lost ack");l.close();opened.pop();const b=fake(undefined,a.markers),l2=durable(r,b.value);expect((await l2.accept(ev())).status).toBe("duplicate");expect(b.calls).toEqual([]);});
 test("partial sink restart sends only unfinished sink with stable key",async()=>{const r=root();let fail=true;const calls:string[]=[];const e:OutboundEmitter={hasDiscord:async()=>false,hasGitHub:async()=>false,emitDiscord:async(_d,_c,k)=>{calls.push(`d:${k}`)},emitGitHub:async(_d,_c,k)=>{calls.push(`g:${k}`);if(fail)throw Error("down")}};const l=durable(r,e);await expect(l.accept(ev())).rejects.toThrow("down");l.close();opened.pop();fail=false;await durable(r,e).accept(ev());expect(calls.filter(x=>x.startsWith("d:"))).toHaveLength(1);expect(new Set(calls.filter(x=>x.startsWith("g:"))).size).toBe(1);});
 test("single-flight prevents concurrent duplicate emissions",async()=>{const f=fake(),l=new AgentEventLedger(registry,f.value);const [a,b]=await Promise.all([l.accept(ev()),l.accept(ev())]);expect([a.status,b.status].sort()).toEqual(["accepted","duplicate"]);expect(f.calls).toHaveLength(2);});
 test("full event conflict and keyed MAC reject attacker recomputation",async()=>{const r=root(),l=durable(r,fake().value);await l.accept(ev());await expect(l.accept(ev({agent:"other"}))).rejects.toThrow("conflict");l.close();opened.pop();const s=JSON.parse(readFileSync(db(r),"utf8"));s.records["agent-event-v1:livesiang:e1"].event.agent="tampered";writeFileSync(db(r),JSON.stringify(s),{mode:0o600});expect(()=>durable(r,fake().value)).toThrow("MAC mismatch");});
});

describe("authority, replay and filesystem",()=>{
 test("authenticated ingress binds trusted Discord row and resumes identical replay",async()=>{expect(()=>new AgentEventLedger(registry,fake().value,undefined,undefined,{authorId:OWNER,key:Buffer.alloc(32)})).toThrow("key invalid");const l=new AgentEventLedger(registry,fake().value,undefined,()=>"2026-08-14T15:45:01.000Z",{authorId:OWNER,key:AUTH});const unsigned={event:ev(),authorId:OWNER,authorIsBot:false,channelId:ROUTES[0]!.destination,projectRoute:"livesiang",nonce:"nonce-1",issuedAt:"2026-08-14T15:45:00.000Z"};const good={...unsigned,signature:signAgentEventIngress(unsigned,AUTH)};expect((await l.acceptAuthenticated(good)).status).toBe("accepted");expect((await l.acceptAuthenticated(good)).status).toBe("duplicate");for(const m of[{authorIsBot:true},{channelId:"bad"},{authorId:"x"}]){const u={...unsigned,...m,nonce:`n-${JSON.stringify(m)}`};const x={...u,signature:signAgentEventIngress(u,AUTH)} as AuthenticatedAgentEventIngress;await expect(l.acceptAuthenticated(x)).rejects.toThrow("ingress");}});
 test("requires MAC key and safe 0700 non-symlink root",()=>{const r=root();expect(()=>new AgentEventLedger(registry,fake().value,db(r))).toThrow("MAC key required");chmodSync(r,0o755);expect(()=>new AgentEventLedger(registry,fake().value,db(r),undefined,undefined,STORE)).toThrow("root unsafe");const p=root(),link=join(p,"link");symlinkSync(r,link);expect(()=>new AgentEventLedger(registry,fake().value,db(link),undefined,undefined,STORE)).toThrow("unsafe");});
 test("lease probe deterministically holds matching/fresh-reused/unknown and reclaims stale-reused",()=>{const now=1_000_000,owner={pid:77,startedAt:100_000,heartbeat:now-100,token:"owner"};const attempt=(probe:LeaseProbe,heartbeat=owner.heartbeat)=>{const r=root();writeFileSync(join(r,"writer.lease"),JSON.stringify({...owner,heartbeat})+"\n",{mode:0o600});return()=>{const l=new AgentEventLedger(registry,fake().value,db(r),undefined,undefined,STORE,probe);opened.push(l);return l;}};const base={pid:88,alive:()=>true,now:()=>now};expect(attempt({...base,startTime:()=>owner.startedAt})).toThrow("lease held");expect(attempt({...base,startTime:()=>owner.startedAt+70_000})).toThrow("lease held");expect(attempt({...base,startTime:()=>undefined})).toThrow("lease held");expect(attempt({...base,startTime:()=>owner.startedAt+70_000},now-31_000)).not.toThrow();});
 test("two processes contend; dead writer lease is recovered",async()=>{const r=root(),url=JSON.stringify(new URL("../src/agent-event-ledger.ts",import.meta.url).href),routes=JSON.stringify(ROUTES),key=JSON.stringify(STORE.toString("hex"));const script=`import {AgentEventLedger} from ${url};import {ProjectRegistry} from ${JSON.stringify(new URL("../src/project-routes.ts",import.meta.url).href)};new AgentEventLedger(new ProjectRegistry(${routes}),{emitDiscord:async()=>{},emitGitHub:async()=>{},hasDiscord:async()=>false,hasGitHub:async()=>false},${JSON.stringify(db(r))},undefined,undefined,Buffer.from(${key},'hex'));`;const owner=durable(r,fake().value);const blocked=Bun.spawn([process.execPath,"-e",script]);expect(await blocked.exited).not.toBe(0);owner.close();opened.pop();const crashed=Bun.spawn([process.execPath,"-e",script]);expect(await crashed.exited).toBe(0);durable(r,fake().value);});
});
