import {describe,expect,test} from "bun:test";
import {AgentEventDaemon,AgentEventLedger,AGENT_EVENT_SCHEMA} from "../src/agent-event-ledger";
import {AgentEventHttpIngress,loadAgentEventDaemonConfig,signTrustedDiscordRow} from "../src/agent-event-daemon";
import {ProjectRegistry} from "../src/project-routes";
const route={name:"livesiang",transport:"discord-text" as const,destination:"1537404238861438996",agent:"03-canon:1",issue:"natkingsize2/liveSiang#15"};
const env={MAW_AGENT_EVENT_HTTP_TOKEN:"A".repeat(32),MAW_AGENT_EVENT_AUTHOR_ID:"1056224550129508415",MAW_AGENT_EVENT_INGRESS_KEY_B64:Buffer.alloc(32,1).toString("base64"),MAW_AGENT_EVENT_STORE_KEY_B64:Buffer.alloc(32,2).toString("base64")};
describe("production daemon seam",()=>{
 test("config rejects missing and weak secrets without echo",()=>{expect(()=>loadAgentEventDaemonConfig({})).toThrow("configuration invalid");expect(()=>loadAgentEventDaemonConfig({...env,MAW_AGENT_EVENT_INGRESS_KEY_B64:Buffer.alloc(32).toString("base64")})).toThrow("configuration invalid");});
 test("trusted Discord signer + HTTP bearer accepts once and rejects nonce replay",async()=>{const cfg=loadAgentEventDaemonConfig(env),calls:string[]=[];const ledger=new AgentEventLedger(new ProjectRegistry([route]),{emitDiscord:async()=>{calls.push("d")},emitGitHub:async()=>{calls.push("g")}},undefined,()=>"2026-08-14T15:45:01.000Z",cfg.authority);const http=new AgentEventHttpIngress(new AgentEventDaemon(ledger),cfg);const signed=signTrustedDiscordRow({authorId:cfg.authority.authorId,authorIsBot:false,channelId:route.destination,projectRoute:route.name,messageId:"1537404238861438997",timestamp:"2026-08-14T15:45:00.000Z",event:{schema:AGENT_EVENT_SCHEMA,project:route.name,kind:"done",event_id:"e-http",agent:"canon",summary:"done",occurred_at:"2026-08-14T15:45:00.000Z"}},cfg.authority);const request=()=>new Request("http://127.0.0.1/agent-event",{method:"POST",headers:{Authorization:`Bearer ${cfg.httpToken}`},body:JSON.stringify(signed)});expect((await http.handle(request())).status).toBe(202);expect((await http.handle(request())).status).toBe(400);expect(calls).toEqual(["d","g"]);});
 test("wrong bearer and bot row fail before ledger",async()=>{const cfg=loadAgentEventDaemonConfig(env);expect(()=>signTrustedDiscordRow({authorId:cfg.authority.authorId,authorIsBot:true,channelId:route.destination,projectRoute:route.name,messageId:"1537404238861438997",timestamp:new Date().toISOString(),event:{} as any},cfg.authority)).toThrow("rejected");const http=new AgentEventHttpIngress(new AgentEventDaemon(new AgentEventLedger(new ProjectRegistry([route]),{emitDiscord:async()=>{},emitGitHub:async()=>{}},undefined,undefined,cfg.authority)),cfg);expect((await http.handle(new Request("http://127.0.0.1/agent-event",{method:"POST",body:"{}"}))).status).toBe(401);});
});
