import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, symlinkSync, writeFileSync, unlinkSync, linkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Broker, NAT_USER_ID } from "../src/broker";
import { keyFromBase64, seal } from "../src/crypto";
import { DurableStore } from "../src/store";
import type { InboundMessage, Route } from "../src/types";
import { DiscordTextAdapter } from "../src/adapter-discord";
import { shouldAdvanceCursor } from "../src/cursor-policy";
import { retryDecision } from "../src/retry";

const key = Buffer.alloc(32, 7); const route: Route = { name: "gate", transport: "discord-text", destination: "thread-1" };
const msg = (id = "m-1", authorId = NAT_USER_ID, routeName = "thread-1"): InboundMessage => ({ messageId: id, authorId, content: "approve", route: routeName });
function fixture(root = mkdtempSync(join(tmpdir(), "maw-broker-"))) { const routes = new Map([["thread-1", route]]); const store=new DurableStore(root); return { root, store, broker: new Broker(key, routes, store) }; }

test("owner allow resolves and survives restart dedupe", async () => { const f=fixture(); const e=seal(key,"thread-1","m-1","payload"); expect(await f.broker.receive(msg(),e,"allow")).toMatchObject({status:"resolved",plaintext:"payload"}); const restarted=new Broker(key,new Map([["thread-1",route]]),new DurableStore(f.root)); expect((await restarted.receive(msg(),e,"allow")).status).toBe("replay"); });
test("foreign author is rejected", async () => { const f=fixture(); expect(f.broker.receive(msg("m-2","foreign"),seal(key,"thread-1","m-2","x"),"allow")).rejects.toThrow("foreign author"); });
test("tampered ciphertext is rejected", async () => { const f=fixture(); const e=seal(key,"thread-1","m-3","x"); e.ciphertext=e.ciphertext.slice(0,-2)+"AA"; expect(f.broker.receive(msg("m-3"),e,"allow")).rejects.toThrow("authentication failed"); });
test("wrong route is rejected", async () => { const f=fixture(); const e=seal(key,"other","m-4","x"); expect(f.broker.receive(msg("m-4",NAT_USER_ID,"other"),e,"allow")).rejects.toThrow("wrong route"); });
test("missing key fails closed", () => { expect(()=>keyFromBase64(undefined)).toThrow("broker key missing"); });
test("invalid decision is rejected explicitly", async () => { const f=fixture(); const e=seal(key,"thread-1","m-6","x"); expect(f.broker.receive(msg("m-6"),e,"maybe" as any)).rejects.toThrow("invalid decision"); });
test("audit is durable and contains no plaintext", async () => { const f=fixture(); const e=seal(key,"thread-1","m-5","secret payload","discord-text","deny"); const result=await f.broker.receive(msg("m-5"),e,"deny"); expect(result).not.toHaveProperty("plaintext"); const audit=readFileSync(new DurableStore(f.root).auditPath,"utf8"); expect(audit).not.toContain("secret payload"); expect(audit).toContain('"event":"resolved"'); });
test("nonce and tag truncation fail closed", async () => { const f=fixture(); const e=seal(key,"thread-1","m-7","x"); e.nonce=e.nonce.slice(0,-2); expect(f.broker.receive(msg("m-7"),e,"allow")).rejects.toThrow(); });
test("transport and decision tamper is rejected", async () => { const f=fixture(); const e=seal(key,"thread-1","m-8","x"); e.transport="voice"; expect(f.broker.receive(msg("m-8"),e,"allow")).rejects.toThrow(); });
test("symlink store path is rejected", () => { const root=mkdtempSync(join(tmpdir(),"maw-broker-link-")); const target=mkdtempSync(join(tmpdir(),"maw-broker-target-")); const link=join(root,"store"); symlinkSync(target,link); expect(()=>new DurableStore(link)).toThrow("symlink"); });
test("corrupt resolved state is named", () => { const root=mkdtempSync(join(tmpdir(),"maw-broker-corrupt-")); require("node:fs").writeFileSync(join(root,"resolved.json"),'{"bad":true}'); expect(()=>new DurableStore(root)).toThrow("resolved state corrupt"); });
test("concurrent store instances retain both IDs", () => { const root=mkdtempSync(join(tmpdir(),"maw-broker-concurrent-")); const a=new DurableStore(root); const b=new DurableStore(root); a.markResolved("a"); b.markResolved("b"); expect(new DurableStore(root).has("a")).toBe(true); expect(new DurableStore(root).has("b")).toBe(true); });
test("injection fault leaves pending and restart retries at ack seam", async () => { const f=fixture(); const e=seal(key,"thread-1","m-9","x"); expect(await f.broker.receive(msg("m-9"),e,"allow",async ()=>{throw new Error("SIGKILL seam")})).toMatchObject({status:"pending"}); const restarted=new Broker(key,new Map([["thread-1",route]]),new DurableStore(f.root)); let injected=""; expect(await restarted.receive(msg("m-9"),e,"allow",async p=>{injected=p;return {messageId:"m-9",route:"thread-1",accepted:true}})).toMatchObject({status:"resolved",plaintext:"x"}); expect(injected).toBe("x"); });
test("post-construction hard link is refused without victim write", () => { const f=fixture(); const victim=join(f.root,"victim.log"); writeFileSync(victim,"SAFE"); writeFileSync(join(f.root,"audit.jsonl"),""); unlinkSync(join(f.root,"audit.jsonl")); linkSync(victim,join(f.root,"audit.jsonl")); expect(()=>f.store.audit({at:new Date().toISOString(),event:"error",reason:"x"})).toThrow("unsafe audit file"); expect(readFileSync(victim,"utf8")).toBe("SAFE"); });
test("post-construction FIFO is refused and lock is releasable", () => { const f=fixture(); writeFileSync(join(f.root,"audit.jsonl"),""); unlinkSync(join(f.root,"audit.jsonl")); const fifo=join(f.root,"audit.jsonl"); execFileSync("mkfifo",[fifo]); expect(()=>f.store.audit({at:new Date().toISOString(),event:"error",reason:"x"})).toThrow("unsafe audit file"); unlinkSync(fifo); f.store.audit({at:new Date().toISOString(),event:"error",reason:"lock-released"}); });
test("empty stale lock is reclaimed", () => { const f=fixture(); const lock=join(f.root,"resolved.json.lock"); writeFileSync(lock,""); f.store.audit({at:new Date().toISOString(),event:"error",reason:"x"}); });
test("Discord normalization carries bot and webhook identity", () => { const x=new DiscordTextAdapter().normalize({id:"d",channel_id:"thread-1",author:{id:"bot",bot:true},webhook_id:"wh",content:"x",timestamp:"t"}); expect(x).toMatchObject({transport:"discord-text",authorIsBot:true,webhookId:"wh"}); });
test("cursor policy advances only terminal deny/resolve outcomes", () => { expect(shouldAdvanceCursor("OWNER_MISMATCH")).toBe(true); expect(shouldAdvanceCursor("CHANNEL_NOT_PROJECT")).toBe(true); expect(shouldAdvanceCursor("CONFIG_FAILURE")).toBe(false); expect(shouldAdvanceCursor("INJECTOR_FAILURE")).toBe(false); });
test("Discord retry semantics are bounded and fail closed", () => { expect(retryDecision(429)).toMatchObject({retry:true}); expect(retryDecision(401)).toMatchObject({retry:false,hold:true}); expect(retryDecision(403)).toMatchObject({retry:false,hold:true}); expect(retryDecision(503)).toMatchObject({retry:true,hold:true}); });
test("route registry transport mismatch is rejected", async () => { const f=fixture(); const voice={...route,transport:"pipecat-voice"}; const b=new Broker(key,new Map([["thread-1",voice]]),new DurableStore(f.root)); const e=seal(key,"thread-1","m-10","x","discord-text","allow"); expect(b.receive(msg("m-10"),e,"allow")).rejects.toThrow("wrong route or transport"); });
test("invalid downstream acknowledgement remains pending", async () => { const f=fixture(); const e=seal(key,"thread-1","m-11","x"); expect(await f.broker.receive(msg("m-11"),e,"allow",async ()=>({messageId:"other",route:"thread-1",accepted:true}))).toMatchObject({status:"pending"}); });
