import { expect, test } from "bun:test";
import { chmodSync, existsSync, mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Broker, NAT_USER_ID } from "../src/broker";
import { DiscordPollSource } from "../src/discord-source";
import { BrokerIngress } from "../src/ingress";
import { DiscordRestClient, BrokerRunner, DurableCursor, loadRunnerSecrets, PersistentLease } from "../src/runner";
import { DurableStore } from "../src/store";
import type { DownstreamInjector, Route } from "../src/types";

const key = Buffer.alloc(32, 7); const route: Route = { name: "gate", transport: "discord-text", destination: "thread-1" };
const row = (id: string, content = "approve", timestamp = id) => ({ id, channel_id: "thread-1", author: { id: NAT_USER_ID }, content, timestamp });
function runner(rows: unknown[], root = mkdtempSync(join(tmpdir(), "maw-runner-")), injector?: DownstreamInjector) { const broker = new Broker(key, new Map([["thread-1", route]]), new DurableStore(join(root, "store")), NAT_USER_ID); return { root, run: new BrokerRunner({ source: new DiscordPollSource({ getMessages: async () => rows }, "thread-1"), ingress: new BrokerIngress(broker), cursor: new DurableCursor(join(root, "cursor.json")), key, injector }) }; }
const response = (status: number, body: unknown = [], retryAfter?: string) => ({ ok: status >= 200 && status < 300, status, headers: new Headers(retryAfter ? { "retry-after": retryAfter } : {}), json: async () => body });

test("runner processes old-to-new messages with default counting injector and durable cursor", async () => { const f = runner([row("2", "approve", "2026-01-02"), row("1", "approve", "2026-01-01")]); expect(await f.run.runOnce()).toEqual({ processed: 2, held: false }); expect(f.run.injectionCount).toBe(2); expect(JSON.parse(readFileSync(join(f.root, "cursor.json"), "utf8"))).toEqual({ before: "2" }); expect(statSync(join(f.root, "cursor.json")).mode & 0o777).toBe(0o600); });
test("REST client retries 429 using Retry-After without logging token", async () => { let calls = 0; const token = "TOKEN-MUST-NOT-LEAK"; const client = new DiscordRestClient(token, async () => ++calls === 1 ? response(429, [], "0.001") : response(200, [row("1")]), async () => {}); expect(await client.getMessages("thread-1")).toEqual([row("1")]); expect(calls).toBe(2); });
test("REST client holds 401 without retry", async () => { let calls = 0; const client = new DiscordRestClient("TOKEN-MUST-NOT-LEAK", async () => { calls++; return response(401); }, async () => {}); await expect(client.getMessages("thread-1")).rejects.toThrow("held"); expect(calls).toBe(1); });
test("runner holds its cursor when a REST 401 is returned", async () => { const root = mkdtempSync(join(tmpdir(), "maw-runner-401-")); const broker = new Broker(key, new Map([["thread-1", route]]), new DurableStore(join(root, "store")), NAT_USER_ID); const client = new DiscordRestClient("TOKEN-MUST-NOT-LEAK", async () => response(401), async () => {}); const run = new BrokerRunner({ source: new DiscordPollSource(client, "thread-1"), ingress: new BrokerIngress(broker), cursor: new DurableCursor(join(root, "cursor.json")), key }); expect(await run.runOnce()).toEqual({ processed: 0, held: true }); expect(() => readFileSync(join(root, "cursor.json"))).toThrow(); });
test("malformed rows are skipped while a later valid row advances cursor", async () => { const f = runner([row("3", "approve", "2026-01-03"), { id: "2", channel_id: "thread-1" }, row("1", "approve", "2026-01-01")]); expect(await f.run.runOnce()).toEqual({ processed: 2, held: false }); expect(JSON.parse(readFileSync(join(f.root, "cursor.json"), "utf8"))).toEqual({ before: "3" }); });
test("replay is not injected twice", async () => { const root = mkdtempSync(join(tmpdir(), "maw-runner-replay-")); let injections = 0; const inject = async (_plaintext: string, messageId: string, routeName: string) => { injections++; return { messageId, route: routeName, accepted: true as const }; }; const first=runner([row("1")], root, inject).run; expect(await first.runOnce()).toEqual({ processed: 1, held: false }); first.close(); const second=runner([row("1")], root, inject).run; expect(await second.runOnce()).toEqual({ processed: 1, held: false }); second.close(); expect(injections).toBe(1); });
test("cursor persists across runner restart", async () => { const root = mkdtempSync(join(tmpdir(), "maw-runner-restart-")); const first=runner([row("1")], root).run; expect(await first.runOnce()).toEqual({ processed: 1, held: false }); first.close(); let before: string | undefined; const broker = new Broker(key, new Map([["thread-1", route]]), new DurableStore(join(root, "store")), NAT_USER_ID); const run = new BrokerRunner({ source: new DiscordPollSource({ getMessages: async (_channel, cursor) => { before = cursor; return []; } }, "thread-1"), ingress: new BrokerIngress(broker), cursor: new DurableCursor(join(root, "cursor.json")), key }); await run.runOnce(); run.close(); expect(before).toBe("1"); });
test("secret configuration errors never include supplied token", () => { const token = "TOKEN-MUST-NOT-LEAK"; expect(() => loadRunnerSecrets({ DISCORD_BOT_TOKEN: token, MAW_BROKER_KEY_B64: "bad", MAW_BROKER_OWNER_ID: "bad" })).toThrow("broker runner configuration invalid"); try { loadRunnerSecrets({ DISCORD_BOT_TOKEN: token, MAW_BROKER_KEY_B64: "bad", MAW_BROKER_OWNER_ID: "bad" }); } catch (error) { expect(String(error)).not.toContain(token); } });
test("secret file must be mode 0600", () => { const root = mkdtempSync(join(tmpdir(), "maw-runner-secret-")); const path = join(root, "secrets.json"); writeFileSync(path, JSON.stringify({ DISCORD_BOT_TOKEN: "x", MAW_BROKER_KEY_B64: Buffer.alloc(32).toString("base64"), MAW_BROKER_OWNER_ID: NAT_USER_ID })); chmodSync(path, 0o644); expect(() => loadRunnerSecrets({ MAW_BROKER_SECRETS_FILE: path })).toThrow("broker runner configuration invalid"); });
test("secrets load from either env or a mode-0600 file", () => { const encoded = Buffer.alloc(32, 9).toString("base64"); expect(loadRunnerSecrets({ DISCORD_BOT_TOKEN: "env-token", MAW_BROKER_KEY_B64: encoded, MAW_BROKER_OWNER_ID: NAT_USER_ID })).toMatchObject({ discordBotToken: "env-token", ownerId: NAT_USER_ID }); const root = mkdtempSync(join(tmpdir(), "maw-runner-secret-good-")); const path = join(root, "secrets.json"); writeFileSync(path, JSON.stringify({ DISCORD_BOT_TOKEN: "file-token", MAW_BROKER_KEY_B64: encoded, MAW_BROKER_OWNER_ID: NAT_USER_ID }), { mode: 0o600 }); expect(loadRunnerSecrets({ MAW_BROKER_SECRETS_FILE: path })).toMatchObject({ discordBotToken: "file-token", ownerId: NAT_USER_ID }); });
test("second process fails while lease owner lives, then crash permits reclaim", async () => { const root = mkdtempSync(join(tmpdir(), "maw-runner-lease-")); const module = new URL("../src/runner.ts", import.meta.url).href; const code = `import { PersistentLease } from ${JSON.stringify(module)}; new PersistentLease(process.argv.at(-1)); setInterval(() => {}, 1000);`; const first = spawn(process.execPath, ["-e", code, root], { stdio: "ignore" }); for (let i=0; i<100 && !existsSync(join(root, "runner.lease")); i++) await new Promise(resolve => setTimeout(resolve, 10)); expect(existsSync(join(root, "runner.lease"))).toBe(true); const second = spawn(process.execPath, ["-e", code, root], { stdio: "ignore" }); const [secondCode] = await once(second, "exit") as [number | null]; expect(secondCode).not.toBe(0); first.kill("SIGKILL"); await once(first, "exit"); const reclaimed = new PersistentLease(root); expect(existsSync(join(root, "runner.lease"))).toBe(true); reclaimed.release(); });
