import { createHash, createHmac, timingSafeEqual, randomUUID } from "node:crypto";
import { chmodSync, closeSync, constants, existsSync, fchmodSync, fstatSync, ftruncateSync, fsyncSync, lstatSync, mkdirSync, openSync, readFileSync, renameSync, unlinkSync, writeFileSync, writeSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";
import { execFileSync } from "node:child_process";
import type { ProjectRegistry } from "./project-routes";

export const AGENT_EVENT_SCHEMA = "maw.broker.agent-event.v1";
export const AGENT_EVENT_KINDS = ["progress", "done", "blocked"] as const;
export type AgentEventKind = (typeof AGENT_EVENT_KINDS)[number];
export const AGENT_EVENT_IDEMPOTENCY_PREFIX = "agent-event-v1";
export type AgentEvent = { schema:string; project:string; kind:string; event_id:string; agent:string; summary:string; occurred_at:string };
export type AgentEventReceipt = { status:"accepted"|"duplicate"; schema:string; project:string; kind:AgentEventKind; event_id:string; idempotencyKey:string; receivedAt:string; discordDestination:string; githubIssue:string };
export type AuthenticatedAgentEventIngress = { event:unknown; authorId:string; authorIsBot:boolean; channelId:string; projectRoute:string; nonce:string; issuedAt:string; signature:string };
export type IngressAuthority = { authorId:string; key:Buffer };
export class AgentEventError extends Error { constructor(readonly code:"MALFORMED_EVENT"|"KIND_REJECTED"|"UNKNOWN_PROJECT"|"IDEMPOTENCY_CONFLICT"|"UNAUTHENTICATED_INGRESS",message:string){super(message);this.name="AgentEventError";} }
const EVENT_KEYS=["agent","event_id","kind","occurred_at","project","schema","summary"];
const ID_RE=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$/; const TIME_RE=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const sha=(v:string|Buffer)=>createHash("sha256").update(v).digest("hex");
export function canonicalJson(v:unknown):string{if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return `[${v.map(canonicalJson).join(",")}]`;return `{${Object.keys(v as object).sort().map(k=>`${JSON.stringify(k)}:${canonicalJson((v as any)[k])}`).join(",")}}`;}
export function buildAgentEventIdempotencyKey(project:string,eventId:string){return `${AGENT_EVENT_IDEMPOTENCY_PREFIX}:${project}:${eventId}`;}
export function validateAgentEvent(body:unknown,registry:ProjectRegistry){const b=body as Partial<AgentEvent>;if(!b||typeof b!=="object"||Array.isArray(b)||Object.keys(b).sort().join("\0")!==EVENT_KEYS.slice().sort().join("\0"))throw new AgentEventError("MALFORMED_EVENT","event key set invalid");if(b.schema!==AGENT_EVENT_SCHEMA||!ID_RE.test(b.project??"")||!ID_RE.test(b.event_id??"")||!ID_RE.test(b.agent??"")||typeof b.summary!=="string"||!b.summary||b.summary.length>2000||!TIME_RE.test(b.occurred_at??"")||!Number.isFinite(Date.parse(b.occurred_at!))||new Date(b.occurred_at!).toISOString()!==b.occurred_at)throw new AgentEventError("MALFORMED_EVENT","event fields invalid");if(!(AGENT_EVENT_KINDS as readonly string[]).includes(b.kind!))throw new AgentEventError("KIND_REJECTED","event kind rejected");const route=registry.project(b.project!);if(!route)throw new AgentEventError("UNKNOWN_PROJECT","unknown project");return{event:b as AgentEvent&{kind:AgentEventKind},idempotencyKey:buildAgentEventIdempotencyKey(b.project!,b.event_id!),discordDestination:route.destination,githubIssue:route.issue};}
export interface OutboundEmitter{emitDiscord(destination:string,content:string,idempotencyKey?:string):Promise<void>;emitGitHub(issueRef:string,comment:string,idempotencyKey?:string):Promise<void>;hasDiscord?(destination:string,idempotencyKey:string):Promise<boolean>;hasGitHub?(issueRef:string,idempotencyKey:string):Promise<boolean>}
function strongKey(key:Buffer){if(key.length<32||key.equals(Buffer.alloc(key.length)))throw new Error("agent-event key invalid");return key;}
export function signAgentEventIngress(input:Omit<AuthenticatedAgentEventIngress,"signature">,key:Buffer){return createHmac("sha256",strongKey(key)).update(canonicalJson(input)).digest("hex");}
type Sink="discord"|"github"; type SinkState={status:"pending"|"delivered";idempotencyKey:string;deliveredAt?:string};
type RecordRow={event:AgentEvent&{kind:AgentEventKind};eventDigest:string;receipt:AgentEventReceipt;sinks:Record<Sink,SinkState>};
type AuditRow={at:string;action:"queued"|"sink-delivered"|"accepted"|"replay"|"conflict";idempotencyKey:string;eventDigest:string;sink?:Sink;prevHash:string|null;hash:string};
type NonceRow={requestDigest:string;issuedAt:string};type Core={version:3;records:Record<string,RecordRow>;audit:AuditRow[];nonces:Record<string,NonceRow>}; type Snapshot=Core&{snapshotMac:string};
function safeRoot(root:string){if(resolve(root)!==root)throw new Error("agent-event store root must be absolute");if(!existsSync(root))mkdirSync(root,{mode:0o700});let part=root;for(;;){const s=lstatSync(part);if(!s.isDirectory()||s.isSymbolicLink())throw new Error("agent-event store ancestry unsafe");if(part===root&&(s.uid!==process.getuid()||(s.mode&0o077)!==0))throw new Error("agent-event store root unsafe");if(part!==root&&(s.mode&0o002)!==0&&(s.mode&0o1000)===0)throw new Error("agent-event store ancestry unsafe");const next=dirname(part);if(next===part)break;part=next;}}
function safeRead(path:string){const a=lstatSync(path);if(!a.isFile()||a.isSymbolicLink()||a.uid!==process.getuid()||(a.mode&0o777)!==0o600||a.nlink!==1)throw new Error("agent-event snapshot unsafe");const fd=openSync(path,constants.O_RDONLY|((constants as any).O_NOFOLLOW??0));try{const b=fstatSync(fd);if(b.ino!==a.ino||b.dev!==a.dev||!b.isFile()||b.nlink!==1)throw new Error("agent-event snapshot raced");return readFileSync(fd,"utf8");}finally{closeSync(fd);}}
class Lease {
  private fd!: number;
  private inode!: number;
  private readonly token = randomUUID();
  private readonly startedAt = processStartedAt(process.pid) ?? Date.now();
  private heartbeat = 0;
  readonly path: string;
  constructor(root: string) {
    this.path = `${root}/writer.lease`;
    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        this.fd = openSync(this.path, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | ((constants as any).O_NOFOLLOW ?? 0), 0o600);
        this.inode=fstatSync(this.fd).ino;this.write(Date.now());return;
      } catch {
        let owner:{pid:number;startedAt:number;heartbeat:number;token:string};
        try { owner=JSON.parse(safeRead(this.path));if(!owner||!Number.isSafeInteger(owner.pid)||!Number.isSafeInteger(owner.startedAt)||!Number.isSafeInteger(owner.heartbeat)||typeof owner.token!=="string")throw Error(); } catch { throw new Error("agent-event writer lease corrupt"); }
        let alive=true;try{process.kill(owner.pid,0)}catch{alive=false}const actual=alive?processStartedAt(owner.pid):undefined;const reused=actual!==undefined&&Math.abs(actual-owner.startedAt)>60_000;
        if(!alive||(reused&&Date.now()-owner.heartbeat>30_000)){unlinkSync(this.path);continue;}
        throw new Error("agent-event writer lease held");
      }
    }
    throw new Error("agent-event writer lease unavailable");
  }
  refresh(){const raw=JSON.parse(safeRead(this.path));const st=lstatSync(this.path);if(st.ino!==this.inode||raw.pid!==process.pid||raw.startedAt!==this.startedAt||raw.token!==this.token)throw new Error("agent-event writer lease lost");this.write(Date.now());}
  private write(heartbeat:number){this.heartbeat=heartbeat;ftruncateSync(this.fd,0);fchmodSync(this.fd,0o600);writeSync(this.fd,canonicalJson({pid:process.pid,startedAt:this.startedAt,heartbeat,token:this.token})+"\n",0,"utf8");fsyncSync(this.fd);}
  close(){try{const raw=JSON.parse(safeRead(this.path));const st=lstatSync(this.path);if(st.ino===this.inode&&raw.pid===process.pid&&raw.startedAt===this.startedAt&&raw.heartbeat===this.heartbeat&&raw.token===this.token)unlinkSync(this.path);}catch{}finally{closeSync(this.fd);}}
}
function processStartedAt(pid:number){try{const out=execFileSync("ps",["-p",String(pid),"-o","etime="],{encoding:"utf8"}).trim();const m=/^(?:(\d+)-)?(?:(\d+):)?(\d+):(\d+)$/.exec(out);if(!m)return undefined;const elapsed=(((Number(m[1]??0)*24+Number(m[2]??0))*60+Number(m[3]))*60+Number(m[4]))*1000;return Date.now()-elapsed;}catch{return undefined;}}
export class AgentEventLedger {
  private records = new Map<string, RecordRow>(); private audit: AuditRow[] = [];
  private nonces = new Map<string,NonceRow>(); private lease?: Lease; private serial: Promise<void> = Promise.resolve();
  constructor(private registry:ProjectRegistry,private emitter:OutboundEmitter,private path?:string,private now:()=>string=()=>new Date().toISOString(),private authority?:IngressAuthority,private storeKey?:Buffer){
    if(authority) strongKey(authority.key);
    if(path){if(!storeKey)throw new Error("agent-event store MAC key required");if(typeof emitter.hasDiscord!=="function"||typeof emitter.hasGitHub!=="function")throw new Error("agent-event idempotent sink reconciliation required");strongKey(storeKey);const root=dirname(path);safeRoot(root);if(basename(path)!=="ledger.json")throw new Error("agent-event snapshot name invalid");this.lease=new Lease(root);try{if(existsSync(path))this.load();}catch(e){this.close();throw e;}}
  }
  close(){this.lease?.close();this.lease=undefined;}
  private mac(core:Core){return createHmac("sha256",this.storeKey!).update(canonicalJson(core)).digest("hex");}
  private load(){let p:Snapshot;try{p=JSON.parse(safeRead(this.path!));}catch(e){throw new Error(`agent-event snapshot corrupt: ${e instanceof Error?e.message:"invalid"}`);}if(Object.keys(p).sort().join(",")!=="audit,nonces,records,snapshotMac,version"||p.version!==3||!p.records||!Array.isArray(p.audit)||!p.nonces||typeof p.nonces!=="object")throw new Error("agent-event snapshot schema invalid");const{snapshotMac,...core}=p;if(!/^[0-9a-f]{64}$/.test(snapshotMac)||!timingSafeEqual(Buffer.from(this.mac(core)),Buffer.from(snapshotMac)))throw new Error("agent-event snapshot MAC mismatch");this.validateNested(p);this.records=new Map(Object.entries(p.records));this.audit=p.audit;this.nonces=new Map(Object.entries(p.nonces));if(!this.verifyAuditChain())throw new Error("agent-event audit chain broken");}
  private validateNested(p:Snapshot){for(const[key,row]of Object.entries(p.records)){if(key!==buildAgentEventIdempotencyKey(row.event?.project,row.event?.event_id)||row.eventDigest!==sha(canonicalJson(row.event))||Object.keys(row.sinks??{}).sort().join(",")!=="discord,github")throw new Error("agent-event record invalid");for(const sink of ["discord","github"] as const){const s=row.sinks[sink];if(!s||!(["pending","delivered"] as string[]).includes(s.status)||s.idempotencyKey!==`${key}:${sink}`||(s.status==="delivered")!==(typeof s.deliveredAt==="string"))throw new Error("agent-event sink state invalid");}}for(const row of p.audit){if(!row||typeof row!=="object"||!(["queued","sink-delivered","accepted","replay","conflict"] as string[]).includes(row.action)||!ID_RE.test(row.idempotencyKey.replaceAll(":","_"))||!/^[0-9a-f]{64}$/.test(row.eventDigest)||!/^[0-9a-f]{64}$/.test(row.hash))throw new Error("agent-event audit invalid");}for(const[nonce,row]of Object.entries(p.nonces)){if(!ID_RE.test(nonce)||Object.keys(row??{}).sort().join(",")!=="issuedAt,requestDigest"||!/^[0-9a-f]{64}$/.test(row.requestDigest)||!TIME_RE.test(row.issuedAt))throw new Error("agent-event nonce invalid");}}
  private persist(){if(!this.path)return;this.lease?.refresh();const core:Core={version:3,records:Object.fromEntries(this.records),audit:this.audit,nonces:Object.fromEntries(this.nonces)};const out:Snapshot={...core,snapshotMac:this.mac(core)};const tmp=`${this.path}.tmp-${process.pid}-${randomUUID()}`;const fd=openSync(tmp,constants.O_WRONLY|constants.O_CREAT|constants.O_EXCL|((constants as any).O_NOFOLLOW??0),0o600);try{writeFileSync(fd,canonicalJson(out)+"\n");fchmodSync(fd,0o600);fsyncSync(fd);}finally{closeSync(fd);}renameSync(tmp,this.path);const d=openSync(dirname(this.path),constants.O_RDONLY);try{fsyncSync(d);}finally{closeSync(d);}chmodSync(this.path,0o600);}
  private add(action:AuditRow["action"],key:string,digest:string,sink?:Sink){const prev=this.audit.at(-1)?.hash??null;const core={at:this.now(),action,idempotencyKey:key,eventDigest:digest,...(sink?{sink}:{}),prevHash:prev};this.audit.push({...core,hash:sha(canonicalJson(core))});}
  verifyAuditChain(){let prev:string|null=null;for(const row of this.audit){const{hash,...core}=row;if(row.prevHash!==prev||sha(canonicalJson(core))!==hash)return false;prev=hash;}return true;} get auditRows(){return this.audit as readonly AuditRow[];}
  private authenticate(input:AuthenticatedAgentEventIngress){if(!this.authority)throw new AgentEventError("UNAUTHENTICATED_INGRESS","ingress authority missing");if(!/^[1-9]\d{16,19}$/.test(input.authorId)||!/^[1-9]\d{16,19}$/.test(input.channelId)||!ID_RE.test(input.nonce)||!TIME_RE.test(input.issuedAt)||new Date(input.issuedAt).toISOString()!==input.issuedAt)throw new AgentEventError("UNAUTHENTICATED_INGRESS","ingress provenance invalid");const{signature,...unsigned}=input;const expected=signAgentEventIngress(unsigned,this.authority.key);if(!/^[0-9a-f]{64}$/.test(signature)||!timingSafeEqual(Buffer.from(signature),Buffer.from(expected))||input.authorId!==this.authority.authorId||input.authorIsBot)throw new AgentEventError("UNAUTHENTICATED_INGRESS","ingress authentication failed");const requestDigest=sha(canonicalJson(unsigned));const prior=this.nonces.get(input.nonce);if(prior&&prior.requestDigest!==requestDigest)throw new AgentEventError("UNAUTHENTICATED_INGRESS","ingress nonce conflict");if(!prior&&Math.abs(Date.parse(this.now())-Date.parse(input.issuedAt))>300_000)throw new AgentEventError("UNAUTHENTICATED_INGRESS","ingress provenance invalid");const valid=validateAgentEvent(input.event,this.registry);if(input.projectRoute!==valid.event.project||input.channelId!==valid.discordDestination)throw new AgentEventError("UNAUTHENTICATED_INGRESS","ingress route binding failed");if(!prior){this.nonces.set(input.nonce,{requestDigest,issuedAt:input.issuedAt});this.persist();}return valid;}
  private single<T>(fn:()=>Promise<T>):Promise<T>{const run=this.serial.then(fn,fn);this.serial=run.then(()=>{},()=>{});return run;}
  acceptAuthenticated(input:AuthenticatedAgentEventIngress){return this.single(()=>this.acceptValidated(this.authenticate(input)));} accept(body:unknown){return this.single(()=>{if(this.authority)throw new AgentEventError("UNAUTHENTICATED_INGRESS","authenticated ingress required");return this.acceptValidated(validateAgentEvent(body,this.registry));});}
  private async acceptValidated(v:ReturnType<typeof validateAgentEvent>):Promise<AgentEventReceipt>{const{event,idempotencyKey,discordDestination,githubIssue}=v;const digest=sha(canonicalJson(event));let row=this.records.get(idempotencyKey);if(row&&row.eventDigest!==digest){this.add("conflict",idempotencyKey,digest);this.persist();throw new AgentEventError("IDEMPOTENCY_CONFLICT","idempotency conflict");}const duplicate=!!row;if(!row){const receipt={status:"accepted" as const,schema:event.schema,project:event.project,kind:event.kind,event_id:event.event_id,idempotencyKey,receivedAt:this.now(),discordDestination,githubIssue};row={event,eventDigest:digest,receipt,sinks:{discord:{status:"pending",idempotencyKey:`${idempotencyKey}:discord`},github:{status:"pending",idempotencyKey:`${idempotencyKey}:github`}}};this.records.set(idempotencyKey,row);this.add("queued",idempotencyKey,digest);this.persist();}const content=`[${event.kind}] ${event.agent} @ ${event.project}: ${event.summary}`;for(const sink of ["discord","github"] as const){if(row.sinks[sink].status==="delivered")continue;const marker=row.sinks[sink].idempotencyKey;const found=sink==="discord"?await this.emitter.hasDiscord?.(discordDestination,marker):await this.emitter.hasGitHub?.(githubIssue,marker);if(found!==true){if(sink==="discord")await this.emitter.emitDiscord(discordDestination,content,marker);else await this.emitter.emitGitHub(githubIssue,content,marker);}row.sinks[sink]={...row.sinks[sink],status:"delivered",deliveredAt:this.now()};this.add("sink-delivered",idempotencyKey,digest,sink);this.persist();}this.add(duplicate?"replay":"accepted",idempotencyKey,digest);this.persist();return{...row.receipt,status:duplicate?"duplicate":"accepted"};}
}
export class AgentEventDaemon{constructor(readonly ledger:AgentEventLedger){}ingest(input:AuthenticatedAgentEventIngress){return this.ledger.acceptAuthenticated(input)}close(){this.ledger.close()}}
